inventory_icon = '//i[@class="fa fa-fw fa-archive"]'
opening_stock_link = '//span[contains(text(),"Opening Stock")]//ancestor::a'
opening_stock_heading = '//h4[contains(text(),"Opening Stock")]'
create_opening_stock_link = '//a[contains(text(),"Create Opening Stock")]'
all_stores_option = '//span[contains(text(),"All Stores") and @class="default-name"]'
store_select_dropdown = '//i[@class="fa fa-angle-down ml-3 fs-14"]'
store_field = '//input[@id="store-selector-input"]'
store_first_option = '(//ul[@class="m-0 filter-dropdown vertical-scroll"]/li)[1]'
stockpoint_option = '//div[@class="multiselect__tags"]'
first_stock_point = '(//ul[@role="listbox"]/li)[1]'