dashboard_sidebar_option = '//i[@class="fa fa-fw fa-home "]'
product_categories_c = '//i[@class="fa fa-fw fa-book "]'
product_categories_sidebar_option_c = '//span[text()="Products Categories"]'
carry_bags_sidebar_option_c = '//span[text()="Carry Bags"]'
add_category = '//button[@id="addCategory"]'
new_category_title = '//h5[@id="addCategoryModal___BV_modal_title_" and contains(text(),"New category")]'
new_category_name = '//input[@placeholder="Category name"]'
new_category_close_icon = '//button[@class="close"]'
create_new_category_button = '//button[@class="btn btn-primary" and contains(text(),"Create")]'
category_already_exist = '//div[@class="toast-body" and contains(text(),"Category already exist")]'
category_created_successfully = '//div[@class="toast-body" and contains(text(),"Category created successfully")]'
inventory_c = '//i[@class="fa fa-fw fa-archive"]'
item_allocation_c = '//span[text()="Item Allocation"]'

# Item allocation'
item_allocation_title = '//h4[@class="m-0 box-title" and contains(text(),"Item allocation")]'
new_item_allocation_button = '//a[@class="btn btn-primary" and contains(text(),"New item allocation")]'
title_item_allocation = '//p[text()="Please select a store first from the "]'
all_stores_dropdown = '//span[@class="default-name" and contains(text(),"All Stores")]'
search_store = '//input[@placeholder="Search store"]'
first_option_store_dropdown = 'class="m-0 filter-dropdown vertical-scroll"'
new_item_allocation_title = '//h3[@class="m-0 pull-left box-title" and contains(text(),"New Item Allocation")]'
add_multiple = '//button[@class="btn text-button btn-secondary" and contains(text(),"Add Multiple")]'
add_multiple_products_title = '//h5[@class="modal-title" and contains(text(),"Add Multiple Products")]'
select_value = '//select[@class="form-select"]'
category_option = '//option[@value="category"]'
search_category = '//input[@placeholder="Search to add"]'
first_option_search_category = '//span[@class="multiselect__option multiselect__option--highlight"]'

# Carry Bag
search_store_carry_bag = '//input[@class="input is-rounded"]'
barcode_carry_bag = '//tr[@class="collapse show"]//td[@data-v-02c9d4fc][2]'

# Product Creation
product_sidebar_option_c = '//span[text()="Products"]'
product_title = '//h3[@class="m-0 box-title" and contains(text(),"Products")]'
new_product_button = '//a[@class="btn float-lg-right float-right ml-0 btn-primary" and contains(text(),"New product")]'
new_product_title = '//h3[@class="m-0 pull-left box-title" and contains(text(),"New Product")]'
save_product_button = '//button[@class="btn pull-right btn-primary" and contains(text(),"Save Product")]'
product_name = '(//input[@placeholder="Enter product name"])[1]'
product_department = '(//input[@placeholder="Enter product name"])[2]'
product_brand = '//input[@placeholder="Enter brand name"]'
select_category_product = '//div[@class="vue-treeselect__placeholder vue-treeselect-helper-zoom-effect-off"]'
enter_category_name = '//input[@class="vue-treeselect__input"]'
product_description = '//textarea[@placeholder="Add a detailed description for the product"]'
product_mrp = '//input[@placeholder="Enter MRP"]'
product_rsp = '//input[@placeholder="Enter RSP"]'
product_special_price = '//input[@placeholder="Enter special price"]'
unit_and_inventory = '//li[@class="fs-14" and contains(text(),"Units & Inventory")]'
choose_unit_inventory = '//span[@class="multiselect__placeholder" and contains(text(),"Choose attribute")]'
enter_inventory_name = '//input[@placeholder="Choose attribute"]'
product_variant = '//li[@class="fs-14" and contains(text(),"Product Variants")]'
product_barcode_variant = '//input[@placeholder="Barcode"]'
mrp_variant = '//input[@placeholder="Maximum Retail Price"]'
rsp_variant = '//input[@placeholder="Selling Price"]'
special_price_variant = '//input[@placeholder="Special Price"]'

# Retail PriceBook
retail_pb_sidebar_option_c = '//span[text()="Retail Pricebook"]'
retail_pb_title = '//h4[@class="pull-left m-0 page-title" and contains(text(),"Retail Pricebook")]'
create_new_pb_retail_button = '//button[@class="btn pull-right btn-primary" and contains(text(),"Create New")]'
new_pb_option_retail = '//a[@class="text-grey"]//li[text()="New Pricebook"]'
new_retail_pb_title = '//h4[@class="pull-left mb-0 box-title" and contains(text(),"New Retail Pricebook")]'
price_book_name = '//input[@placeholder="Enter price book name"]'
scan_auto_switch_off_btn = '//button[@class="btn border-none fs-12 btn-primary text-dark bg-grey" and contains(text(),"Scan auto-switch OFF")]'
switch_to_search_btn = '//i[@class="fa fa-search mr-2"]'

allocate_pb_window_title = '//h5[@class="modal-title" and contains(text(),"Allocate Pricebook")]'
allocate_pb_window_close_icon = '//button[@class="close"]'
allocate_pb_window_cancel_btn = '//button[@class="btn btn text-button btn-secondary" and contains(text(),"Cancel")]'
allocate_pb_window_allocate_btn = '//button[@class="btn ml-3 btn-primary" and contains(text(),"Allocate Now")]'
allocate_retail_pb_title = '//h4[@class="pull-left mb-0 box-title" and contains(text(),"Allocate Retail Pricebook")]'
store_select_allocate_retail_pb = '//input[@placeholder="Search store"]'
first_store_select_checkbox = '//input[@class="form-input-check float-none"]'
continue_button_allocate_retail_pb = '//button[@class="btn pull-right btn-primary" and contains(text(),"Continue")]'
