email = '//input[@id="emailInput"]'
password = '//input[@id="passwordInput"]'
continue_button = '//button[@id="continueBtn"]'
dashboard = '//h3[@data-toggle="modal" and text()="Dashboard"]'
invoice_icon = '//i[@class="fa fa-fw fa-shopping-cart "]'
product_icon = '//i[@class="fa fa-fw fa-book "]'
promotion_icon = '//i[@class="fa fa-fw fa-bullhorn "]'
pos_terminal_logo = '//i[@class="fa fa-fw fa-money "]//ancestor::a'
pos_terminal_link = '//span[text()="POS Terminals"]//ancestor::a'
