settings_tab = '//img[@id="nav-settings"]//ancestor::a'
serial_information_tab = '//a[contains(text(),"Serial Information")]'
serial_info_heading = '//h5[contains(text(),"Serial Information")]'
revoke_license_button = '//button[@id="revoke-lic-btn" and text()="Revoke License"]'
revoke_modal_title = '//h5[contains(text(),"Enter license key") and @class="modal-title"]'
license_key_input = '//input[@id="enter-lic"]'
revoke_license_confirm_button = '//button[@id="revoke-lic-confirm"]'
activate_device_heading = '//h2[text()="Activate Device"]'
profile_info_heading = '//h5[contains(text(),"Profile Information")]'